

INSERT INTO FUNCIONARIO F (F.ID, F.NOME, F.LOGIN, F.SENHA, F.TIPO_FUNCIONARIO) VALUES (1, 'JOÃO LUCAS', 'joao.lucas', '1234', 0);
INSERT INTO FUNCIONARIO F (F.ID, F.NOME, F.LOGIN, F.SENHA, F.TIPO_FUNCIONARIO) VALUES (2, 'ANDRÉ SILVA', 'andre.silva', '1234', 1);
INSERT INTO FUNCIONARIO F (F.ID, F.NOME, F.LOGIN, F.SENHA, F.TIPO_FUNCIONARIO) VALUES (3, 'ALINE SILVA', 'aline.silva', '1234', 1);
